// <auto-generated />
namespace PRI_NaszSamochód.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbgenkeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbgenkeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201705251119407_dbgenkeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
